name: data

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - ".github/workflows/data.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: zhibek/osm-toolbox:1.3.0
      env:
        DOCKER: false
        AREA: europe
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - run: cd ./data && ./scripts/build-tiles.sh

    - name: Set variable to check if anything changed
      id: is_updated
      run: |-
        echo "##[set-output name=changed;]$(ls -al ./data/files/*.pmtiles | wc -l)"

    - name: Copy data files
      if: steps.is_updated.outputs.changed != 0
      run: |-
        cp ./data/files/*.pmtiles ./public/files/railways.pmtiles

    - name: Commit data files
      if: steps.is_updated.outputs.changed != 0
      run: |
        git config --global --add safe.directory $(pwd)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./public/files
        git commit -m "Update at $(date +'%Y-%m-%d %H:%M')"

    - name: Push changes
      if: steps.is_updated.outputs.changed != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}