name: data

on:
  push:
    branches:
      - main
    paths:
      - "data/**"

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data
    container:
      image: zhibek/osm-toolbox:1.2.0
      env:
        DOCKER: false
        AREA: england
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v3

    - run: bash -x scripts/build-tiles.sh