name: data

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - ".github/data.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data
    container:
      image: zhibek/osm-toolbox:1.3.0
      env:
        DOCKER: false
        AREA: monaco
      volumes:
        - .:/workspace
      options: --workdir /workspace
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - run: bash -x scripts/build-tiles.sh

    - name: Set variable to check if anything changed
      id: is_updated
      run: |-
        echo "##[set-output name=changed;]$(ls -al ./files/*.pmtiles | wc -l)"

    - name: Copy data files
      if: steps.is_updated.outputs.changed != 0
      run: |-
        cp ./files/*.pmtiles ../public/files/railways.pmtiles

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: steps.is_updated.outputs.changed != 0
      with:
        commit_message: Update tiles